language: java
jdk: openjdk11

install: true
script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)


# need superuser for docker
sudo: required
services:
  - docker
before_deploy:
  - git add --all
deploy:
  script: ls
  skip_cleanup: true
  cleanup: false
  #zip_file: target
  provider: elasticbeanstalk
  region:  "eu-central-1"
  app: "docker-chapp"
  env: "DockerChapp-env"
  bucket_name: elasticbeanstalk-eu-central-1-034445363307
  bucket_path: "docker-chapp"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

