# need superuser for docker
sudo: required
services:
  - docker

language: java
jdk: openjdk11

install: true
script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - git status
  - git add --all
  - git
  - zip travis.zip
  - ls
deploy:
  skip_cleanup: true
  cleanup: false
  zip_file: /
  provider: elasticbeanstalk
  region:  "eu-central-1"
  app: "docker-chapp"
  env: "DockerChapp-env"
  bucket_name: elasticbeanstalk-eu-central-1-034445363307
  bucket_path: "docker-chapp"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
after_deploy:
  - git status
  - ls
