version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - CHAPP_GOOGLE_CLIENT_ID=${CHAPP_GOOGLE_CLIENT_ID}
      - CHAPP_GOOGLE_CLIENT_SECRET={CHAPP_GOOGLE_CLIENT_SECRET}